name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]
    name: Test on Java ${{ matrix.java }}
    env:
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run tests + coverage (JaCoCo)
        run: mvn -B clean verify

      - name: Upload JaCoCo HTML report (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-site-java-${{ matrix.java }}
          path: target/site/jacoco/

      - name: Upload coverage to Coveralls (parallel)
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: target/site/jacoco/jacoco.xml
          format: jacoco
          parallel: true
          flag-name: java-${{ matrix.java }}

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          
